const { join, sleep, consoleCmd, check, results, waitWindow, title, itemName, SERVER } = require('./lib');
const fs = require('fs'); const path = require('path');
const logLen = () => fs.readFileSync(path.join(SERVER, 'server.log'), 'utf8').length;
const logSince = n => fs.readFileSync(path.join(SERVER, 'server.log'), 'utf8').slice(n).replace(/\u001b\[[0-9;]*m/g, '');
(async () => {
  const a = await join('Tester1');
  consoleCmd('hatcases hat give Tester1 halo_shiny'); await sleep(800);
  a.chat('/hats equip halo_shiny'); await sleep(800);
  let l = logLen(); consoleCmd('data get entity Tester1 equipment.head'); await sleep(800);
  let out = logSince(l);
  check('server: head is carved_pumpkin', /minecraft:carved_pumpkin/.test(out), out.slice(0, 300));
  check('server: Protection IV on hat', /"minecraft:protection": 4/.test(out));
  check('server: +3 armor, +2 armor_toughness', /amount: 3\.0d.*type: "minecraft:armor"|type: "minecraft:armor".*amount: 3\.0d/s.test(out) && /minecraft:armor_toughness/.test(out) && /amount: 2\.0d/.test(out));
  check('server: custom_model_data 90 (same model as PTrap)', /floats: \[90\.0f\]/.test(out));
  consoleCmd('give Tester1 enchanted_book[stored_enchantments={thorns:2}]'); await sleep(800);
  a.chat('/hat'); let w = await waitWindow(a, w => /Мои шляпки/.test(title(w)));
  await a.clickWindow(w.slots.findIndex((s, i) => i < 45 && s && /Нимб/.test(itemName(s) || '')), 1, 0); await sleep(400);
  await a.clickWindow(11, 0, 0); await sleep(500);
  await a.clickWindow(a.currentWindow.slots.findIndex((s, i) => i >= 27 && s && s.name === 'enchanted_book'), 0, 0); await sleep(1200);
  a.closeWindow(a.currentWindow);
  l = logLen(); consoleCmd('data get entity Tester1 equipment.head'); await sleep(800);
  out = logSince(l);
  check('server: worn hat refreshed with book enchant (thorns 2) + base protection', /"minecraft:thorns": 2/.test(out) && /"minecraft:protection": 4/.test(out), out.slice(0, 400));
  a.chat('/hat menu'); w = await waitWindow(a, w => /Магазин шляп/.test(title(w)));
  await sleep(500);
  const lore = JSON.stringify(a.currentWindow.slots[0]);
  check('shop item shows price 75 ₽ in lore', /75 ₽/.test(lore), lore.slice(0, 200));
  a.quit(); const f = results.filter(r => !r.ok).length;
  console.log(`SUMMARY ${results.length - f}/${results.length} passed`); await sleep(500); process.exit(0);
})().catch(e => { console.error('CRASH', e); process.exit(1); });
